"""empty message

Revision ID: 18f677459bd0
Revises: 
Create Date: 2019-03-17 11:01:52.623276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f677459bd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('priority', sa.VARCHAR(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'priority')
    # ### end Alembic commands ###
