"""empty message

Revision ID: 254bdf1d45a5
Revises: 18f677459bd0
Create Date: 2019-03-17 11:33:43.345371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '254bdf1d45a5'
down_revision = '18f677459bd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('category_id', sa.Integer(), nullable=False))
    op.drop_column('tickets', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('category', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('tickets', 'category_id')
    # ### end Alembic commands ###
