"""empty message

Revision ID: ea5b37f8ec31
Revises: 254bdf1d45a5
Create Date: 2019-03-17 11:43:32.993388

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea5b37f8ec31'
down_revision = '254bdf1d45a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('priority', sa.VARCHAR(length=128), nullable=False))
    op.drop_column('users', 'priority')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('priority', mysql.VARCHAR(length=128), nullable=False))
    op.drop_column('tickets', 'priority')
    # ### end Alembic commands ###
