--Users Table

INSERT INTO Users(Username, [Level], FirstName, LastName, Email, Password, Active)
VALUES
('amrhein.c16', 1, 'Claudia', 'Amrhein','amrhein.c16 @partaonline.org', 'password', 1),
('mfletch', 1, 'Marcia', 'Fletcher','mfletch@partaonline.org', 'password', 1),
('jurisch.k88', 1, 'Kelly', 'Jurisch','jurisch.k88@partaonline.org', 'password', 1),
('btrautman', 1, 'Brian', 'Trautman','btrautman@partaonline.org', 'password', 1),
('mpriest', 1, 'Mary', 'Priest','mpriest@partaonline.org', 'password', 1),
('lwiley', 1, 'Lita', 'Wiley','lwiley@partaonline.org', 'password', 1),
('cjones', 1, 'Chuck', 'Jones','cjones@partaonline.org', 'password', 1),
('jneilly', 1, 'Jordyn', 'Neilly','jneilly@partaonline.org', 'password', 1),
('schrader.r38', 1, 'Rebecca', 'Schrader','schrader.r38@partaonline.org', 'password', 1),
('aboyd', 1, 'Ashley', 'Boyd','aboyd@partaonline.org', 'password', 1),
('reaton', 1, 'Rachelle', 'Eaton','reaton@partaonline.org', 'password', 1),
--('TBD', 1, 'TBD', '','TBD', 'password', 1),
('swestover', 1, 'Sharon', 'Westover','swestover@partaonline.org', 'password', 1),
('hairston.f18', 1, 'Frank', 'Hairston','hairston.f18@partaonline.org', 'password', 1),
('emapes', 1, 'Emilee', 'Mapes','emapes@partaonline.org', 'password', 1),
('cpopik', 1, 'Clayton', 'Popik','cpopik@partaonline.org', 'password', 1),
('choward22', 1, 'Carlell', 'Howard','choward22@partaonline.org', 'password', 1),
('kcalcei', 1, 'Kylie', 'Calcei','kcalcei@partaonline.org', 'password', 1),
('aagema', 1, 'Allen', 'Agema','aagema@partaonline.org', 'password', 1),
('cshafer', 1, 'Christine', 'Shafer','cshafer@partaonline.org', 'password', 1),
('mdowdle', 1, 'Manuel', 'Dowdle','mdowdle@partaonline.org', 'password', 1),
('ecleveng', 1, 'Eric', 'Clevenger','ecleveng@partaonline.org', 'password', 1),
('ehellekson2', 1, 'Eric', 'Hellekson','ehellekson2@partaonline.org', 'password', 1),
('sbeacham', 1, 'Steve', 'Beacham','sbeacham@partaonline.org', 'password', 1),
('jzisk', 1, 'John', 'Zisk','jzisk@partaonline.org', 'password', 1),
('wgroff', 1, 'Will', 'Groff','wgroff@partaonline.org', 'password', 1),
('jtakacs9', 1, 'Joe', 'Takacs','jtakacs9@partaonline.org', 'password', 1),
('jbackhurst', 1, 'Jack', 'Backhurst','jbackhurst@partaonline.org', 'password', 1),
('ddonofrio', 1, 'Drew', 'Donofrio','ddonofrio@partaonline.org', 'password', 1),
('froush', 1, 'Faith', 'Roush','froush@partaonline.org', 'password', 1),
('dcrowe', 1, 'Dominic', 'Crowe','dcrowe@partaonline.org', 'password', 1),
('rstuart', 1, 'Ron', 'Stuart','rstuart@partaonline.org', 'password', 1),
('dleggett', 1, 'David', 'Leggett','dleggett@partaonline.org', 'password', 1),
('jhamrick', 1, 'Joanne', 'Hamrick','jhamrick@partaonline.org', 'password', 1),
('rmorrison', 1, 'Robert', 'Morrison','rmorrison@partaonline.org', 'password', 1),
('astevens', 1, 'Andrea', 'Stevens','astevens@partaonline.org', 'password', 1),
('dcapriola', 1, 'Denise', 'Capriola','dcapriola@partaonline.org', 'password', 1),
('knull', 1, 'Karen', 'Null','knull@partaonline.org', 'password', 1),
('vhayes', 1, 'Vickie', 'Hayes','vhayes@partaonline.org', 'password', 1),
('solaugh', 1, 'Sharon', 'O''Laughlin','solaugh@partaonline.org', 'password', 1),
('mhanus', 1, 'Melissa', 'Hanus','mhanus@partaonline.org', 'password', 1),
('jjacob', 1, 'John', 'Jacobs','jjacob@partaonline.org', 'password', 1),
('schisme1', 1, 'Sara', 'Schismenos','schisme1@partaonline.org', 'password', 1),
('dwiard', 1, 'David', 'Wiard','dwiard@partaonline.org', 'password', 1),
('jmadden', 1, 'Jamie', 'Madden','jmadden@partaonline.org', 'password', 1),
('amijiblee', 1, 'Anwar', 'Mijiblee','amijiblee@partaonline.org', 'password', 1),
('dsmith1', 1, 'Dennis', 'Smith','dsmith1@partaonline.org', 'password', 1),
('eportis', 1, 'Ebony', 'Portis','eportis@partaonline.org', 'password', 1),
('kbritton', 1, 'Kyan', 'Britton','kbritton@partaonline.org', 'password', 1),
('nkyer', 1, 'Nicole', 'Kyer','nkyer@partaonline.org', 'password', 1),
('sthomas', 1, 'Sandee', 'Thomas','sthomas@partaonline.org', 'password', 1),
('aphile', 1, 'Alisa', 'Phile','aphile@partaonline.org', 'password', 1),
('rschultz', 1, 'Randy', 'Schultz','rschultz@partaonline.org', 'password', 1),
('mpennington', 1, 'Mick', 'Pennington','mpennington@partaonline.org', 'password', 1),
('mtrickett', 1, 'Mike', 'Trickett','mtrickett@partaonline.org', 'password', 1),
('rhedding', 1, 'Roy', 'Hedding','rhedding@partaonline.org', 'password', 1),
('dshort', 1, 'David', 'Short','dshort@partaonline.org', 'password', 1),
('dfrazier', 1, 'Daryl', 'Frazier','dfrazier@partaonline.org', 'password', 1),
('smacdonald', 1, 'Sherrie', 'MacDonald','smacdonald@partaonline.org', 'password', 1),
('cunder', 1, 'Charles', 'Underwood','cunder@partaonline.org', 'password', 1),
('hmccoy', 1, 'Heather', 'McCoy','hmccoy@partaonline.org', 'password', 1),
--('TBD', 1, 'TBD', '','TBD', 'password', 1),
('mhuang', 1, 'Mike', 'Huang','mhuang@partaonline.org', 'password', 1),
('kshumate3', 1, 'Kelli', 'Shumate','kshumate3@partaonline.org', 'password', 1),
('hliu32', 1, 'Hao', 'Liu','hliu32@kent.edu', 'password', 1),
('bswital1', 1, 'Ben', 'Switalski','bswital1@kent.edu', 'password', 1),
('kshumat1', 1, 'Kelli', 'Shumate','kshumat1@kent.edu', 'password', 1),
('jsomwaru', 1, 'Jacob', 'Somwaru','jsomwaru@kent.edu', 'password', 1),
('tnaungay', 1, 'Taylor', 'Naungayan','tnaungay@kent.edu', 'password', 1),
('administrator', 1, 'Administrator', '','administrator@partaonline.org', 'password', 1)

--Categories
